### ISSUE TITLE
Add obstacle for battle environment

### ISSUE THREAD

**Issue by Dimaspadma** [gac-research-club/adefagia-dev#34]
Obstacle type:
- Block
   example: Mountain, Building, etc.

purpose: 
- Blocking robot movement

**Comment by alifianadexe** [comment]
Any development on this branch? if not then lets me to build

**Comment by alifianadexe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Battle Mechanic : Add Random Obstacle](https://trello.com/c/PF293MTG/37-battle-mechanic-add-random-obstacle)
